language: java

jdk:
 - oraclejdk7

notifications:
  email: false
  irc: "chat.freenode.net#qabel"

install:
 - redis-server &
 - sudo apt-get install python-pip npm nodejs
 - sudo pip install virtualenv
 - git clone https://github.com/qabel/qabel-drop
 - virtualenv qabel-drop
 - source qabel-drop/bin/activate
 - pip install -r qabel-drop/requirements.txt
 - cd qabel-drop
 - ./drop_server.py &
 - cd ..
 - git clone https://github.com/Qabel/qabel-storage.git
 - cd qabel-storage
 - npm install
 - mkdir data
 - node app.js &
 - cd ..

script:
 - ./gradlew check
