language: java

jdk:
 - oraclejdk7

notifications:
  email: false

install:
 - redis-server > /dev/null 2>&1 &
 - sudo apt-get install python-pip npm nodejs
 - sudo pip install virtualenv
 - git clone https://github.com/hartmannaf/qabel.git
 - cd qabel
 - git submodule init
 - git submodule update
 - rm -r qabel-core/*
 - cd ..  
 - mv !(qabel) ./qabel/qabel-core/
 - cd qabel
 - virtualenv qabel-drop 
 - source qabel-drop/bin/activate 
 - pip install -r qabel-drop/requirements.txt  

script:
 - travis_wait ./gradlew check
